# Dev config - All of Norway (used by photon-dev.yml for variant 'no')
ADRESSE_URL=https://nedlasting.geonorge.no/geonorge/Basisdata/MatrikkelenAdresse/CSV/Basisdata_0000_Norge_25833_MatrikkelenAdresse_CSV.zip
STEDSNAVN_URL=https://nedlasting.geonorge.no/geonorge/Basisdata/Stedsnavn/GML/Basisdata_0000_Norge_25833_Stedsnavn_GML.zip
STOPPLACE_URL=https://storage.googleapis.com/marduk-production/tiamat/Current_latest.zip
OSM_URL=https://storage.googleapis.com/ror-osmdata-prd/osm-data/norway-latest.osm.pbf
POI_URL=https://raw.githubusercontent.com/entur/geocoder-data/refs/heads/main/festivals_netex_poi.xml
POI2_URL=https://raw.githubusercontent.com/entur/geocoder-data/refs/heads/main/events_norway_poi.xml
