name: 'Resolve Docker Image Tag'
description: 'Resolve tag to the actual semantic version tag from container registry'

inputs:
  registry:
    description: 'Docker registry (e.g., eu.gcr.io/entur-system-1287)'
    required: false
    default: eu.gcr.io/entur-system-1287
  image_name:
    description: 'Docker image name'
    required: true
  image_tag:
    description: 'Image tag to resolve'
    required: true
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true

outputs:
  resolved_tag:
    description: 'The resolved image tag'
    value: ${{ steps.resolve.outputs.resolved_tag }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate with GCP
      if: inputs.image_tag == 'latest'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Resolve image tag
      id: resolve
      shell: bash
      run: |
        RESOLVED_TAG=$(${{ github.action_path }}/resolve-tag.sh "${{ inputs.registry }}" "${{ inputs.image_name }}" "${{ inputs.image_tag }}")
        echo "resolved_tag=$RESOLVED_TAG" >> $GITHUB_OUTPUT
        
        echo "### Image Tag Resolution" >> $GITHUB_STEP_SUMMARY
        echo "**In:** \`${{ inputs.image_tag }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Out:** \`$RESOLVED_TAG\`" >> $GITHUB_STEP_SUMMARY
