name: "[Internal] Docker Security Scan"

inputs:
  image_name:
    description: "Image name with tag (e.g. image:tag)"
    required: true

runs:
  using: composite

  steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

    - name: Configure Docker for GCR
      shell: bash
      run: gcloud auth configure-docker eu.gcr.io --quiet

    - name: Pull image from GCR
      shell: bash
      run: docker pull eu.gcr.io/entur-system-1287/${{ inputs.image_name }}

    - name: Scan for vulnerabilities
      uses: anchore/scan-action@v7
      id: scan
      with:
        image: eu.gcr.io/entur-system-1287/${{ inputs.image_name }}
        by-cve: true
        fail-build: false
        severity-cutoff: critical

    - name: Upload vulnerability report to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: 'grype-scan'


