name: Docker Security Scan

inputs:
  image:
    description: "Image name with tag (e.g. image:tag)"
    required: true
  registry:
    description: 'Docker registry URL'
    required: false
    default: 'eu.gcr.io/entur-system-1287'
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      shell: bash
      run: |
        REGISTRY_DOMAIN=$(echo "${{ inputs.registry }}" | cut -d'/' -f1)
        gcloud auth configure-docker ${REGISTRY_DOMAIN} --quiet

    - name: Pull image from GCR
      shell: bash
      run: docker pull ${{ inputs.registry }}/${{ inputs.image }}

    - name: Scan for vulnerabilities
      uses: anchore/scan-action@v7
      id: scan
      with:
        image: ${{ inputs.registry }}/${{ inputs.image }}
        by-cve: true
        fail-build: false
        severity-cutoff: critical

    - name: Upload vulnerability report to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: 'grype-scan'

    - name: Write scan summary
      shell: bash
      if: always()
      run: |
        echo "## Docker Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** ${{ inputs.registry }}/${{ inputs.image }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Status:** ${{ steps.scan.outcome }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.scan.outputs.success }}" = "false" ]; then
          echo "**⚠️ Critical vulnerabilities detected!**" >> $GITHUB_STEP_SUMMARY
        else
          echo "**✅ No critical vulnerabilities found.**" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "View full report in the [Security tab](https://github.com/${{ github.repository }}/security/code-scanning)." >> $GITHUB_STEP_SUMMARY

