FROM gradle:9.1-jdk21-alpine AS build-image

WORKDIR /srv
SHELL ["/bin/ash", "-co", "pipefail"]

COPY . ./
RUN gradle --no-daemon :converter:build

RUN curl -sfL https://nedlasting.geonorge.no/geonorge/Basisdata/MatrikkelenAdresse/CSV/Basisdata_03_Oslo_25833_MatrikkelenAdresse_CSV.zip | jar -xv
RUN curl -sfL https://nedlasting.geonorge.no/geonorge/Basisdata/Stedsnavn/GML/Basisdata_03_Oslo_25833_Stedsnavn_GML.zip | jar -xv
RUN ./geocoder-convert -m Basis*/*.csv -g Basisdata_03_Oslo_25833_Stedsnavn_GML.gml -o nominatim.ndjson && \
    rm -rf Basis*

RUN curl -sfL https://storage.googleapis.com/marduk-production/tiamat/03_Oslo_latest.zip | jar -xv
RUN ./geocoder-convert -a -s tiamat*.xml -o nominatim.ndjson && \
    rm tiamat*.xml

RUN ./geocoder-convert -a -p converter/src/test/resources/oslo-center.osm.pbf -o nominatim.ndjson && \
    rm converter/src/test/resources/oslo-center.osm.pbf

RUN curl -sfLo photon.jar https://github.com/entur/photon/releases/download/latest-with-prs-2025-10-21/photon-0.7.0.jar

RUN exec java -jar photon.jar \
    -nominatim-import \
    -import-file nominatim.ndjson \
    -languages no,en \
    -extra-tags ALL

FROM scratch

WORKDIR /
COPY --from=build-image /srv/photon.jar photon.jar
COPY --from=build-image /srv/photon_data photon_data
