FROM bellsoft/liberica-runtime-container:jre-21-slim-musl

WORKDIR /srv
COPY ./proxy/build/libs/proxy-all.jar proxy.jar
RUN chown -R 1000:1000 /srv
USER 1000:1000

CMD ["sh", "-c", "exec java -jar proxy.jar"]
