ARG IMPORT_IMAGE=geocoder-import:latest
FROM ${IMPORT_IMAGE} AS import-image

FROM bellsoft/liberica-runtime-container:jre-21-slim-musl

WORKDIR /srv
COPY --from=import-image /photon.jar photon.jar
COPY --from=import-image /photon_data photon_data
RUN chown -R 1000:1000 /srv
USER 1000:1000

CMD ["sh", "-c", "find photon_data -name '*.lock' -delete && exec java -jar photon.jar -default-language no -listen-port ${SERVER_PORT:-2322}"]
