name: 'Build Proxy Image'
description: 'Lint, build, push and scan the proxy Docker image'

inputs:
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true

outputs:
  image_tag:
    description: 'The tag of the built proxy image'
    value: ${{ steps.docker-image.outputs.image_tag }}

runs:
  using: 'composite'
  steps:
    - name: Dockerfile lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: proxy/Dockerfile
        ignore: "DL3018,DL3059"

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: liberica
        java-version: 25

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/dists
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties', 'gradle/*.versions.toml') }}
        restore-keys: |
          gradle-

    - name: Build with Gradle
      shell: bash
      run: ./gradlew --no-daemon :proxy:build

    - name: Cleanup Gradle cache
      shell: bash
      run: |
        rm -f ~/.gradle/caches/journal-1/file-access.bin
        rm -f ~/.gradle/caches/*/gc.properties
        find ~/.gradle/caches -name "*.lock" -delete

    - name: Build and Push
      id: docker-image
      uses: ./.github/actions/docker-build-push
      with:
        image_name: geocoder-proxy
        context: proxy
        push: ${{ inputs.push }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Security Scan
      if: inputs.push == 'true'
      uses: ./.github/actions/docker-scan
      with:
        image: "geocoder-proxy:${{ steps.docker-image.outputs.image_tag }}"
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
