name: 'Generate Docker Image Tag'
description: 'Generate a Docker image tag based on branch and commit SHA'

inputs:
  registry:
    description: 'Docker registry (e.g., eu.gcr.io/entur-system-1287)'
    required: false
    default: eu.gcr.io/entur-system-1287
  image_name:
    description: 'Docker image name'
    required: true

outputs:
  image_tag:
    description: 'The generated image tag (e.g., main.20251103-SHA1234567)'
    value: ${{ steps.generate.outputs.image_tag }}
  base_image:
    description: 'Base image without tag (e.g., eu.gcr.io/entur-system-1287/my-image)'
    value: ${{ steps.generate.outputs.base_image }}
  full_image:
    description: 'Full image reference (e.g., eu.gcr.io/entur-system-1287/my-image:main.20251103-SHA1234567)'
    value: ${{ steps.generate.outputs.full_image }}

runs:
  using: 'composite'
  steps:
    - name: Generate image tag
      id: generate
      shell: bash
      run: |
        IMAGE_TAG=$(${{ github.action_path }}/generate-tag.sh "$GITHUB_SHA" "$GITHUB_REF_NAME"}})
        
        BASE_IMAGE="${{ inputs.registry }}/${{ inputs.image_name }}"
        FULL_IMAGE="${BASE_IMAGE}:${IMAGE_TAG}"
        
        echo "base_image=${BASE_IMAGE}" >> $GITHUB_OUTPUT
        echo "full_image=${FULL_IMAGE}" >> $GITHUB_OUTPUT
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
        
        echo "Base image: ${BASE_IMAGE}"
        echo "Full image reference: ${FULL_IMAGE}"
        echo "Generated image tag: ${IMAGE_TAG}"
        
    - name: Summary
      shell: bash
      run: |
          echo "### Generated Docker Image Tag" >> $GITHUB_STEP_SUMMARY
          echo "**In:** image_name=\`${{ inputs.image_name }}\` registry=\`${{ inputs.registry }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Out:** image_tag=\`${{ steps.generate.outputs.image_tag }}\` base_image=\`${{ steps.generate.outputs.base_image }}\`" >> $GITHUB_STEP_SUMMARY
