name: 'Upload Artifact to Docker Image'
description: 'Upload an artifact by packaging it in a Docker image and pushing to GCR'

inputs:
  file_path:
    description: 'Path to file on disk to upload'
    required: true
  image_name:
    description: 'Name of the Docker image to create (without registry prefix)'
    required: true
  # Note: vars and secrets are not available in composite actions, so they must be passed explicitly
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true
  registry:
    description: 'Docker registry URL'
    required: false
    default: 'eu.gcr.io/entur-system-1287'

outputs:
  image_tag:
    description: 'The tag of the pushed image'
    value: ${{ steps.set-tag.outputs.image_tag }}
  full_image:
    description: 'Full image reference (registry/name:tag)'
    value: ${{ steps.set-tag.outputs.full_image }}

runs:
  using: 'composite'
  steps:
    - name: Create Dockerfile
      id: create-dockerfile
      shell: bash
      run: |
        TEMP_DIR=$(mktemp -d)
        cp "${{ inputs.file_path }}" $TEMP_DIR/
        cd $TEMP_DIR
        cat > Dockerfile << EOF
        FROM scratch
        COPY . .
        EOF
        echo "temp_dir=$TEMP_DIR" >> $GITHUB_OUTPUT
        echo "Created Dockerfile for ${ARTIFACT_FILE}"
        cat Dockerfile

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      shell: bash
      run: |
        REGISTRY_DOMAIN=$(echo "${{ inputs.registry }}" | cut -d'/' -f1)
        gcloud auth configure-docker ${REGISTRY_DOMAIN} --quiet

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate image tag
      id: set-tag
      uses: ./.github/actions/generate-image-tag
      with:
        image_name: ${{ inputs.image_name }}

    - name: Build and push to GCR
      uses: docker/build-push-action@v6
      with:
        context: ${{ steps.create-dockerfile.outputs.temp_dir }}
        file: ${{ steps.create-dockerfile.outputs.temp_dir }}/Dockerfile
        push: true
        tags: |
          ${{ steps.set-tag.outputs.full_image }}
          ${{ steps.set-tag.outputs.base_image }}:latest
        provenance: false

    - name: Summary
      shell: bash
      run: |
        echo "## Docker Artifact Upload" >> $GITHUB_STEP_SUMMARY
        echo "**File path:** \`${{ inputs.file_path }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ steps.set-tag.outputs.full_image }}\`" >> $GITHUB_STEP_SUMMARY

