common:
  env: dev
  ingress:
    host: geocoder-proxy-se.dev.entur.io
    trafficType: public
  deployment:
    minReplicas: 1
  container:
    env:
      - name: PHOTON_URL
        value: http://geocoder-photon-se
      - name: READINESS_QUERY
        value: Stockholm
