common:
  env: prd
  replicas: 4
  container:
    cpu: 250m
    memory: 384Mi
  ingress:
    host: geocoder-proxy.entur.io
    trafficType: api
  hpa:
    spec:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
      maxReplicas: 10
      minReplicas: 4
