name: "[Internal] Build and Push Docker Image"

inputs:
  image_name:
    description: "Docker image name (defaults to repository name)"
    required: false
  dockerfile:
    description: "Path to Dockerfile"
    default: "Dockerfile"
  build_args:
    description: "Build arguments (KEY=VALUE, one per line)"
    required: false
  context:
    description: "Build context"
    default: "."
  push:
    description: "Push image to registry"
    default: "true"
  run-group:
    description: "The run group to use for the job"
    required: false
    default: grp-ubuntu-24.04-2core-x64
outputs:
  image_name:
    description: "Image name"
    value: ${{ steps.build-push.outputs.image_name }}
  image_tag:
    description: "Image tag (git SHA)"
    value: ${{ steps.build-push.outputs.image_tag }}

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with GCP
      if: ${{ inputs.push == 'true' }}
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

    - name: Configure Docker for GCR
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: gcloud auth configure-docker eu.gcr.io --quiet

    - name: Build and push to GCR
      id: build-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: |
          eu.gcr.io/entur-system-1287${{ inputs.image_name }}:${{ github.sha }}
          eu.gcr.io/entur-system-1287/${{ inputs.image_name }}:latest
        build-args: ${{ inputs.build_args }}
        provenance: false
