name: "[Internal] Build and Push Docker Image"

inputs:
  image_name:
    description: "Docker image name (defaults to repository name)"
    required: false
  dockerfile:
    description: "Path to Dockerfile"
    default: "Dockerfile"
  build_args:
    description: "Build arguments (KEY=VALUE, one per line)"
    required: false
  context:
    description: "Build context"
    default: "."
  push:
    description: "Push image to registry"
    default: "true"
  run-group:
    description: "The run group to use for the job"
    required: false
    default: grp-ubuntu-24.04-2core-x64
  workload_identity_provider:
    description: "GCP Workload Identity Provider"
    required: true
  service_account:
    description: "GCP Service Account"
    required: true
outputs:
  image_name:
    description: "Image name"
    value: ${{ steps.set_outputs.outputs.image_name }}
  image_tag:
    description: "Image tag"
    value: ${{ steps.set_outputs.outputs.image_tag }}
  name_with_tag:
    description: "Image name with tag"
    value: ${{ steps.set_outputs.outputs.name_with_tag }}

runs:
  using: 'composite'

  steps:
    - name: Docker Lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ inputs.dockerfile }}
        ignore: "DL3018,DL3059"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with GCP
      if: ${{ inputs.push == 'true' }}
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: gcloud auth configure-docker eu.gcr.io --quiet

    - name: Build and push to GCR
      id: build_push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: |
          eu.gcr.io/entur-system-1287/${{ inputs.image_name }}:${{ github.sha }}
          eu.gcr.io/entur-system-1287/${{ inputs.image_name }}:latest
        build-args: ${{ inputs.build_args }}
        provenance: false

    - name: Set image outputs
      id: set_outputs
      shell: bash
      run: |
        sha="${GITHUB_SHA}"
        echo "image_name=${{ inputs.image_name }}" >> $GITHUB_OUTPUT
        echo "image_tag=$sha" >> $GITHUB_OUTPUT
        echo "name_with_tag=${{ inputs.image_name }}:$sha" >> $GITHUB_OUTPUT

    - name: Scan for vulnerabilities
      uses: anchore/scan-action@v7
      id: scan
      with:
        image: eu.gcr.io/entur-system-1287/${{ inputs.image_name }}
        by-cve: true
        fail-build: false
        severity-cutoff: critical

    - name: Upload vulnerability report to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: 'grype-scan'
