name: Docker Build and Push

inputs:
  image_name:
    description: "Docker image name"
    required: true
  context:
    description: "Build context"
    default: "."
  dockerfile:
    description: "Path to Dockerfile"
    default: "Dockerfile"
  build_args:
    description: "Build arguments (KEY=VALUE, one per line)"
  push:
    description: "Push image to registry"
    default: 'false'
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true
  registry:
    description: 'Docker registry URL'
    required: false
    default: 'eu.gcr.io/entur-system-1287'

outputs:
  image_tag:
    description: "Image tag"
    value: ${{ steps.build-push.outputs.image_tag }}

runs:
  using: 'composite'
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with GCP
      if: ${{ inputs.push == 'true' }}
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      shell: bash
      if: ${{ inputs.push == 'true' }}
      run: |
        REGISTRY_DOMAIN=$(echo "${{ inputs.registry }}" | cut -d'/' -f1)
        gcloud auth configure-docker ${REGISTRY_DOMAIN} --quiet

    - name: Generate image tag
      id: set-tag
      uses: ./.github/actions/generate-image-tag
      with:
        image_name: ${{ inputs.image_name }}

    - name: Build and push to GCR
      uses: docker/build-push-action@v6
      id: build-push
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: |
          ${{ steps.set-tag.outputs.full_image }}
          ${{ steps.set-tag.outputs.base_image }}:latest
        build-args: ${{ inputs.build_args }}
        provenance: false

    - name: Write build and push summary
      shell: bash
      if: always()
      run: |
        echo "## Docker Build & Push Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ steps.set-tag.outputs.full_image }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Build args:** \`${{ inputs.build_args != '' && inputs.build_args || 'None' }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Push requested:** ${{ inputs.push }}" >> $GITHUB_STEP_SUMMARY
