common:
  env: prd
  replicas: 6
  hpa:
    spec:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
      maxReplicas: 10
      minReplicas: 6
