name: 'Download Artifact from Docker Image'
description: 'Download an artifact by extracting it from a Docker image in GCR'

inputs:
  image:
    description: 'Docker image to extract from (format: image-name:tag, without registry prefix)'
    required: true
  destination:
    description: 'Destination directory to extract the artifact to'
    required: true
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true
  registry:
    description: 'Docker registry URL'
    required: false
    default: 'eu.gcr.io/entur-system-1287'

outputs:
  artifact_file:
    description: 'Path to the extracted artifact file'
    value: ${{ steps.extract.outputs.artifact_file }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      shell: bash
      run: |
        REGISTRY_DOMAIN=$(echo "${{ inputs.registry }}" | cut -d'/' -f1)
        gcloud auth configure-docker ${REGISTRY_DOMAIN} --quiet

    - name: Extract artifact from Docker image
      id: extract
      shell: bash
      run: |
        FULL_IMAGE="${{ inputs.registry }}/${{ inputs.image }}"
        echo "Pulling image: $FULL_IMAGE"
        docker pull "$FULL_IMAGE"
        
        # Export and extract image
        TEMP_DIR=$(mktemp -d)
        docker save "$FULL_IMAGE" | tar -xC "$TEMP_DIR"
        
        # Get blob hash from repositories file
        IMAGE_NAME="${{ inputs.image }}"
        REPO_KEY="${{ inputs.registry }}/${IMAGE_NAME%:*}"
        TAG="${IMAGE_NAME##*:}"
        BLOB_HASH=$(jq -r ".\"$REPO_KEY\".\"$TAG\" // empty" "$TEMP_DIR/repositories")
        
        [ -n "$BLOB_HASH" ] || { echo "ERROR: Blob hash not found for $REPO_KEY:$TAG"; jq . "$TEMP_DIR/repositories"; exit 1; }
        
        # Extract file from blob
        echo "Extracting from blob ${BLOB_HASH}"
        mkdir -p "${{ inputs.destination }}"
        
        # Get the filename from the tar archive before extracting
        ARTIFACT_FILENAME=$(tar -tf "$TEMP_DIR/blobs/sha256/$BLOB_HASH" | head -n1)
        echo "Found file in blob: $ARTIFACT_FILENAME"
        
        tar -xf "$TEMP_DIR/blobs/sha256/$BLOB_HASH" -C "${{ inputs.destination }}" || { echo "ERROR: Failed to extract file"; exit 1; }
        
        rm -rf "$TEMP_DIR"
        
        # Set output
        echo "artifact_file=${{ inputs.destination }}/${ARTIFACT_FILENAME}" >> $GITHUB_OUTPUT
        ls -lh "${{ inputs.destination }}/${ARTIFACT_FILENAME}"

    - name: Summary
      shell: bash
      run: |
        echo "### Docker Artifact Download" >> $GITHUB_STEP_SUMMARY
        echo "**In:** image=\`${{ inputs.image }}\` destination=\`${{ inputs.destination }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Out:** artifact_file=\`${{ steps.extract.outputs.artifact_file }}\`" >> $GITHUB_STEP_SUMMARY

