name: 'Download Artifact from Docker Image'
description: 'Download an artifact by extracting it from a Docker image in GCR'

inputs:
  image:
    description: 'Docker image to extract from (format: image-name:tag, without registry prefix)'
    required: true
  artifact_path:
    description: 'Path to file inside the Docker image to extract'
    required: true
  destination:
    description: 'Destination directory to extract the artifact to'
    required: true
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true
  registry:
    description: 'Docker registry URL'
    required: false
    default: 'eu.gcr.io/entur-system-1287'

outputs:
  artifact_file:
    description: 'Path to the extracted artifact file'
    value: ${{ steps.extract.outputs.artifact_file }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      shell: bash
      run: |
        REGISTRY_DOMAIN=$(echo "${{ inputs.registry }}" | cut -d'/' -f1)
        gcloud auth configure-docker ${REGISTRY_DOMAIN} --quiet

    - name: Extract artifact from Docker image
      id: extract
      shell: bash
      run: |
        FULL_IMAGE="${{ inputs.registry }}/${{ inputs.image }}"
        FILE_NAME=$(basename "${{ inputs.artifact_path }}")
        
        echo "Pulling image: $FULL_IMAGE"
        docker pull "$FULL_IMAGE"
        
        echo "Extracting ${FILE_NAME} from image"
        mkdir -p "${{ inputs.destination }}"
        
        # Export image to temp directory
        TEMP_DIR=$(mktemp -d)
        docker save "$FULL_IMAGE" -o "${TEMP_DIR}/image.tar"
        tar -xf "${TEMP_DIR}/image.tar" -C "${TEMP_DIR}"
        
        # Find and extract the file from blob layers
        FOUND=false
        for blob in "${TEMP_DIR}"/blobs/sha256/*; do
          if tar -tf "$blob" "${FILE_NAME}" 2>/dev/null; then
            echo "Found ${FILE_NAME} in blob: $(basename $blob)"
            tar -xf "$blob" -C "${{ inputs.destination }}" "${FILE_NAME}"
            FOUND=true
            break
          fi
        done
        
        if [ "$FOUND" = false ]; then
          echo "ERROR: File ${FILE_NAME} not found in any image layer"
          rm -rf "${TEMP_DIR}"
          exit 1
        fi
        
        # Cleanup
        rm -rf "${TEMP_DIR}"
        
        ARTIFACT_FILE="${{ inputs.destination }}/${FILE_NAME}"
        echo "artifact_file=${ARTIFACT_FILE}" >> $GITHUB_OUTPUT
        
        echo "Artifact extracted to: ${ARTIFACT_FILE}"
        ls -lh "${{ inputs.destination }}/"

    - name: Summary
      shell: bash
      run: |
        echo "## Docker Artifact Download" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ inputs.registry }}/${{ inputs.image }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Artifact path:** \`${{ inputs.artifact_path }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Destination:** \`${{ inputs.destination }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Extracted file:** \`${{ steps.extract.outputs.artifact_file }}\`" >> $GITHUB_STEP_SUMMARY

