name: 'Download Artifact from Docker Image'
description: 'Download an artifact by extracting it from a Docker image in GCR'

inputs:
  image:
    description: 'Docker image to extract from (format: image-name:tag, without registry prefix)'
    required: true
  destination:
    description: 'Destination directory to extract the artifact to'
    required: true
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true
  registry:
    description: 'Docker registry URL'
    required: false
    default: 'eu.gcr.io/entur-system-1287'

outputs:
  artifact_file:
    description: 'Path to the extracted artifact file'
    value: ${{ steps.extract.outputs.artifact_file }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCR
      shell: bash
      run: |
        REGISTRY_DOMAIN=$(echo "${{ inputs.registry }}" | cut -d'/' -f1)
        gcloud auth configure-docker ${REGISTRY_DOMAIN} --quiet

    - name: Extract artifact from Docker image
      id: extract
      shell: bash
      run: ${{ github.action_path }}/extract.sh "${{ inputs.registry }}" "${{ inputs.image }}" "${{ inputs.destination }}"

    - name: Summary
      shell: bash
      run: |
        echo "### Docker Artifact Download" >> $GITHUB_STEP_SUMMARY
        echo "**In:** image=\`${{ inputs.image }}\` destination=\`${{ inputs.destination }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Out:** artifact_file=\`${{ steps.extract.outputs.artifact_file }}\`" >> $GITHUB_STEP_SUMMARY

