# Production config - All of Norway
GEONORGE_AREA=all
STOPPLACE_URL=https://storage.googleapis.com/marduk-production/tiamat/Current_latest.zip
OSM_URL=https://storage.googleapis.com/ror-osmdata-prd/osm-data/norway-latest.osm.pbf
POI_URL=https://raw.githubusercontent.com/entur/geocoder-data/refs/heads/main/festivals_netex_poi.xml
