# Local development config - Oslo only (faster builds)
GEONORGE_AREA=03
STOPPLACE_URL=https://storage.googleapis.com/marduk-production/tiamat/03_Oslo_latest.zip
POI_URL=https://storage.googleapis.com/ent-geocoder-prd/data-sources/events_norway_poi.xml
# Local test file (paths without http/https are treated as local files)
OSM_URL=src/test/resources/oslo-center.osm.pbf
